adds content to pages
INF6420/ss22-he8079 pull request #3
Opened 2022-05-27 23:48 UTC by he8079

Adds new pages: about, contact, curriculum, editing, formatting, proofreading, research, services, tutoring. Adds content set up, images, and links to new pages. Adds content to index page. Adds image files. Slight deviation from original wireframe for index page.

2022-05-30 14:25 UTC, axamei requested changes
Hi @he8079 while the alternative text for the images helps describe the text in the image, we want to make sure the text is also visible to people with low vision. I recommend not using images of text. See: https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html

2022-05-30 14:25 UTC, axamei commented on about.html
> +    <a href="writingsample.html">Writing Sample</a>
Use an unordered list

2022-05-30 14:59 UTC, he8079 commented on about.html
> +    <a href="writingsample.html">Writing Sample</a>
I did the requested changes.

2022-05-31 17:13 UTC, axamei approved these changes

2022-05-31 17:13 UTC, merged